baseURL = "https://wporter.org"
title = "wporter.org"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "personal something"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10
  
  [[menu.main]]
    identifier = "now"
    name = "now"
    title = "now"
    url = "/now"
    weight = 11

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 12

[permalinks]
  posts = "/:title/"